# Generated by Django 4.0.6 on 2022-07-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_rename_nickname_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('target_time', models.DateTimeField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('plan_half_fee', models.IntegerField()),
                ('plan_no_fee', models.IntegerField()),
                ('max_user_num', models.IntegerField()),
                ('room_code', models.CharField(max_length=100)),
                ('plan_period', models.IntegerField()),
                ('leader_id', models.IntegerField()),
                ('negative_percent', models.FloatField()),
                ('user_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='room.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user.user')),
            ],
        ),
    ]
