# Generated by Django 4.0.6 on 2022-07-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_detailplan_content_alter_plan_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
