# Generated by Django 4.0.6 on 2022-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_status',
            field=models.BooleanField(default=True),
        ),
    ]
