# Generated by Django 4.0.6 on 2022-07-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
    ]
